In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3,4,5])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.dtype)
print(arr.shape)
print(arr.size)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1
int64
(5,)
5


In [3]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
2
(2, 4)
8
int64


In [4]:
arr=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]],[[19,20,21],[22,23,24],[25,26,27]]])
print(arr)
print(type(arr))
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
<class 'numpy.ndarray'>
3
(3, 3, 3)
27
int64


In [5]:
# arange(start,stop,step)
# it always return single dimension array
arr=np.arange(10)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
(10,)
10
int64


In [6]:
arr=np.arange(1,13)
print(arr)
arr1=arr.reshape(4,3)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [7]:
arr=np.arange(1,28).reshape(3,1,9)
print(arr)

[[[ 1  2  3  4  5  6  7  8  9]]

 [[10 11 12 13 14 15 16 17 18]]

 [[19 20 21 22 23 24 25 26 27]]]


In [8]:
# indexing
arr=np.arange(1,9)
print(arr)
print(arr[-1])

[1 2 3 4 5 6 7 8]
8


In [32]:
arr=np.arange(1,9).reshape(2,4)
print(arr)
print(arr[0][-1])

[[1 2 3 4]
 [5 6 7 8]]
4


In [9]:
arr=np.arange(1,28).reshape(3,3,3)
print(arr)
print(arr[1][2][2])
print(arr[1][2][1])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
18
17


In [39]:
# iteration
arr=np.array([10,20,30,40,50])
print(arr)
for i in arr:
    print(i)

[10 20 30 40 50]
10
20
30
40
50


In [41]:
arr=np.array([10,20,30,40,50])
print(arr)
for i in range(len(arr)):
    print(i,arr[i])

[10 20 30 40 50]
0 10
1 20
2 30
3 40
4 50


In [44]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
for i in arr:
    for j in i:
        print(j)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
10
20
30
40
50
60
70
80
90


In [48]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)
for i in arr:
    for j in i:
        for k in j:
            print(k,end=" ")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [50]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)
for i in np.nditer(arr):
    print(i,end=" ")

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 

In [52]:
arr=np.arange(1,19).reshape(2,3,3)
print(arr)
for i,j in np.ndenumerate(arr):
    print(i,j)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 1, 0) 4
(0, 1, 1) 5
(0, 1, 2) 6
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
(1, 0, 0) 10
(1, 0, 1) 11
(1, 0, 2) 12
(1, 1, 0) 13
(1, 1, 1) 14
(1, 1, 2) 15
(1, 2, 0) 16
(1, 2, 1) 17
(1, 2, 2) 18


In [1]:
#special filled array
#zeros
import numpy as np
arr=np.zeros(4)
print(arr)

[0. 0. 0. 0.]


In [2]:
arr=np.zeros((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
arr=np.zeros((2,3,3))
print(arr)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [4]:
#ones
arr=np.ones(4)
print(arr)

[1. 1. 1. 1.]


In [6]:
#ones
arr=np.ones((2,4))
print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [7]:
#ones
arr=np.ones((2,3,4))
print(arr)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [8]:
# eye()
arr=np.eye(4)
print(arr)
print(arr[::-1])

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]]


In [9]:
arr=np.eye(3,4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]


In [11]:
# evenly spaced array 
# linspace (start,stop,count)
# both start and stop are inclusive.
arr=np.linspace(0,10,4)
print(arr)

[ 0.          3.33333333  6.66666667 10.        ]


In [12]:
arr=np.random.rand(8)
print(arr)

[0.52212889 0.59366246 0.53934508 0.22223989 0.29019167 0.21300074
 0.91697284 0.00898489]


In [13]:
arr=np.random.randn(5)
print(arr)

[ 0.49377978  0.29041336  1.97895281 -0.08315994  0.1335984 ]


In [14]:
arr=np.random.randint(20,40,(100))
print(arr)

[30 31 25 38 22 31 25 38 37 24 22 23 25 36 21 29 34 36 23 34 21 31 27 32
 37 30 30 35 34 39 35 36 34 22 28 23 20 37 29 28 23 25 30 28 28 21 27 37
 28 34 36 36 36 35 24 21 31 27 20 29 38 30 26 20 23 31 35 32 25 38 28 38
 37 34 25 36 27 29 25 25 30 35 31 31 28 31 30 27 39 37 34 22 32 29 31 24
 30 35 34 29]


In [1]:
 import numpy as np

In [4]:
arr=np.random.randint(21,30,30)
print(arr)

[29 24 23 27 23 29 25 28 29 27 28 23 26 27 24 27 26 23 24 23 22 21 23 21
 23 27 25 22 26 28]
